{{- range .Values.repositories }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .name }}-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
type: Opaque
stringData:
  url: {{ .url }}
  type: {{ .type }}
---
{{- end }}   
 