controller:
  image:
    tag: "2.479.1-lts-jdk17"
  serviceType: ClusterIP
  installPlugins:
    - kubernetes
    - workflow-aggregator
    - git
    - configuration-as-code
  persistence:
    enabled: true
    storageClass: gp2
    size: 10Gi
  ingress:
    enabled: true
    apiVersion: networking.k8s.io/v1
    annotations:
      kubernetes.io/ingress.class: nginx
    hostName: jenkins.example.com
agent:
  enabled: true
