controller:
  image:
    tag: "2.479.1-lts-jdk17"
  serviceType: ClusterIP
  installPlugins:
    - kubernetes
    - workflow-aggregator
    - git
    - configuration-as-code
  persistence:
    enabled: false
agent:
  enabled: true
